# Build Kara and publish release
name: Kara Fedora COPR build CI
on:
  schedule:
    - cron: "0 00 * * *" # At 00:00 daily
env:
  COPR_PROJECT: plasma6-applets-kara
  COPR_USERNAME: deltacopy
  COPR_URL: https://copr.fedorainfracloud.org
  BUILD_REPO: https://github.com/dhruv8sh/kara
  SPEC_FILE: $GITHUB_WORKSPACE/kara.spec
  GIT_USER: DeltaCopy
  REPO_DEV: dhruv8sh
  REPO_NAME: kara
jobs:
  GetLatestVersion:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.step_version.outputs.VERSION }}
    steps:
      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: Get latest version
        id: step_version
        run: |
          # get latest release tag from remote

          latest_release_tag=$(curl -s https://api.github.com/repos/$REPO_DEV/$REPO_NAME/releases/latest |  jq -r '.tag_name')

          echo "INFO: Latest tag = $latest_release_tag"
          echo "INFO: Latest tag = $latest_release_tag"

          if [ ! -z $latest_release_tag ]; then
            latest_tag=$(echo $latest_release_tag | sed 's/v//')
            echo "VERSION=${latest_release_tag}" >> "$GITHUB_OUTPUT"
          else
            echo "Latest tag is unknown"
            exit 1
          fi

      - name: Checkout local
        uses: actions/checkout@v6.0.2
        with:
          repository: ${{ github.repository }}

      - name: Update README
        run: |
          echo ${{ steps.step_version.outputs.VERSION }}
          cat << EOF > README.md
            # $COPR_PROJECT-fedora-copr-ci
            RPM build spec for building Kara on the Fedora COPR.

            This auto triggers Fedora Copr builds: <https://copr.fedorainfracloud.org/coprs/deltacopy/$COPR_PROJECT/builds>

            Upstream: $BUILD_REPO

            ## Active releases available

            - Fedora 42
            - Fedora 43
            - Fedora rawhide

            # Instructions

            Enable the COPR repository then install the package.

            <pre>
            sudo dnf copr enable deltacopy/$COPR_PROJECT
            sudo dnf in $COPR_PROJECT
            </pre>

            #### GitHub Actions scheduled build status

            [![Kara Fedora COPR build CI](https://github.com/DeltaCopy/$COPR_PROJECT-fedora-copr-ci/actions/workflows/kara-fedora-copr-ci.yml/badge.svg)](https://github.com/DeltaCopy/$COPR_PROJECT-fedora-copr-ci/actions/workflows/kara-fedora-copr-ci.yml)

            #### Fedora Copr last build status

            [![Copr build status](https://copr.fedorainfracloud.org/coprs/deltacopy/$COPR_PROJECT/package/$COPR_PROJECT/status_image/last_build.png)](https://copr.fedorainfracloud.org/coprs/deltacopy/$COPR_PROJECT/package/$COPR_PROJECT/)

            ## Latest version
            <img src="https://img.shields.io/badge/plasma6--applets--kara-${{ steps.step_version.outputs.VERSION }}-orange" alt="plasma6--applets--kara-${{ steps.step_version.outputs.VERSION }}">
          EOF
          git config --global user.name $GIT_USER
          git config --global user.email ecto1@duck.com
          git add README.md
          git commit --allow-empty -m "[Kara Fedora COPR CI]: Update version"
          git push --force -v
  UpdateFedoraCOPR:
    needs: GetLatestVersion
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v6.0.2
        with:
          repository: ${{ github.repository }}
          sparse-checkout-cone-mode: false

      - name: Install dependencies
        run: sudo dnf install -y -q copr-cli python3 git gawk

      - name: Get latest tag
        run: |
          # use the tag name but strip the 'v' and '-beta' for the asset name to publish
          tagname=$(echo ${{ needs.GetLatestVersion.outputs.VERSION }} | sed 's/^v//g;s/-beta//g')

          echo "LATEST_TAG=$tagname" >> "$GITHUB_ENV"

          mv ${{ env.SPEC_FILE }}.template ${{ env.SPEC_FILE }}

          sed -i "s/.*%define release_tag.*/%define release_tag ${tagname}/" ${{ env.SPEC_FILE }}
      - name: Update copr-cli configuration
        run: |
          mkdir $HOME/.config
          cat <<EOF > $HOME/.config/copr
          [copr-cli]
          login = ${{ secrets.COPR_BUILD_L }}
          username = ${{ env.COPR_USERNAME }}
          token = ${{ secrets.COPR_BUILD_T }}
          copr_url = ${{ env.COPR_URL }}
          EOF
      - name: Print spec
        run: cat ${{ env.SPEC_FILE }}
      - name: Get latest COPR build information
        run: |
          LATEST_COPR=$(copr-cli get-package ${{ env.COPR_USERNAME }}/${{ env.COPR_PROJECT }} --name ${{ env.COPR_PROJECT }} | python -c 'import json,sys;obj=json.load(sys.stdin);print(obj["latest_build"]["source_package"]["version"]);')

          echo "Latest COPR version = ${LATEST_COPR%-*}"
          echo "Latest Git tag release = ${{ env.LATEST_TAG }}"

          # convert the versions removing the decimal points to ease in comparing them

          copr_version=$(echo "${LATEST_COPR%-*}" | awk -F. '{printf "%03d%03d%03d\n", $1, $2, $3}')
          git_version=$(echo "${{ env.LATEST_TAG }}" | awk -F. '{printf "%03d%03d%03d\n", $1, $2, $3}')

          if [[ $copr_version < $git_version ]] || [[ -z "$LATEST_COPR" ]]; then
              echo "START_BUILD=true" >> "$GITHUB_ENV"
              echo "Starting COPR build"
          else
              echo "START_BUILD=false" >> "$GITHUB_ENV"
              echo "Skipping COPR build"
          fi

      - name: Start COPR build
        if: env.START_BUILD == 'true'
        run: |
          echo "Starting COPR build"
          copr-cli build ${{ env.COPR_PROJECT }} ${{ env.SPEC_FILE }}
